---
fixtures:
  symlinks:
    taskwarrior_server: "#{source_dir}"
  repositories:
    'stdlib':
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'master'
    'vcsrepo':
      repo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo'
      ref: 'master'
