sudo: required
services:
  - docker
language: ruby
rvm:
  - '2.3'

install:
  - gem install bundler
  - bundle install --path vendor/bundle

script:
  - bundle exec rake spec
  - bundle exec rake beaker
